server {
    listen 80;
    root /usr/share/nginx/html;

    location ~* ^/(\d{4}/[^/]+)/ {
        try_files $uri $uri/ /$1/index.html;
    }

    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}
