packages:
  - '*/src'
allowBuilds:
  '[': true
  ']': true
  esbuild: true
  playwright-chromium: true
  vue-demi: true
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@eslint/config-inspector': ^3.0.2
  '@iconify/collections': ^1.0.682
  '@iconify/json': ^2.2.472
  '@slidev/cli': ^52.15.2
  '@slidev/client': ^52.15.2
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^25.7.0
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.2.0
  eslint: ^10.3.0
  eslint-plugin-format: ^2.0.1
  esno: ^4.8.0
  execa: ^9.6.1
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.60.0
  pnpm: ^11.1.1
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.1.3
  seedrandom: ^3.0.5
  slidev-addon-graph: ^1.0.0
  taze: ^19.11.0
  typescript: ^6.0.3
  unocss: ^66.6.8
  vis-data: ^8.0.4
  vis-network: ^10.0.3
  vis-timeline: ^7.7.3
  vue-router: ^5.0.6
  vue-tsc: ^3.2.8
